language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"

script:
  - npm run test

after_success:
  - export LAST_GIT_TAG_VERSION=$(git describe --abbrev=0 --tags) && export LAST_GIT_TAG_VERSION=${LAST_GIT_TAG_VERSION:1}
  - export GIT_TAG_VERSION=$((LAST_GIT_TAG_VERSION+1))

before_deploy:
 - npm run build

# define anchor for standard GCS deploy
-: &gcs_deploy
    provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY
    bucket: "wf-deploy-beta"
    local_dir: ./dist
    skip_cleanup: true
    wait-until-deployed: true

deploy:
  # multiple cases
  # release a snapshot for each commit on any branch except master
  - <<: *gcs_deploy
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != stable
    upload-dir: snapshot/${TRAVIS_COMMIT::7}
  # release a version when on master and commit is tagged
  - <<: *gcs_deploy
    on:
      branch: stable
    upload-dir: stable